app = 'suinfra-rpc-router'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 300
    soft_limit = 200

  [http_service.http_options]
    [http_service.http_options.response]
      pristine = true

      [http_service.http_options.response.headers]
        X-Server = 'suinfra'

  [[http_service.checks]]
    interval = '30s'
    timeout = '3s'
    grace_period = '5s'
    method = 'GET'
    path = '/ping'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
